FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet restore "Tailspin.SpaceGame.Web.csproj"
RUN dotnet build "Tailspin.SpaceGame.Web.csproj" -o /app/out
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Tailspin.SpaceGame.Web.dll"]
